name: 'Pandoc-Thesis'
description: 'This action will run the Pandoc-Thesis toolchain from https://github.com/cagix/pandoc-thesis (Ubuntu runner only)'

inputs:
  rootdoc:
    description: 'root document (.md)'
    required: true
  metadata:
    description: 'Metadata file (.yaml)'
    required: true
  bibfile:
    description: 'Bibtex file (.bib)'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Copy Makefile'
      run: cp ${{ github.action_path }}/Makefile .
      shell: bash

    - name: 'Copy Templates'
      run: cp -r ${{ github.action_path }}/.pandoc .
      shell: bash

    - name: 'Compile document'
      run: make  gfm  ROOT_DOC=${{ inputs.rootdoc }}  METADATA=${{ inputs.metadata }}  BIBFILE=${{ inputs.bibfile }}
      shell: bash

    - name: 'ls -lags'
      run: ls -lags
      shell: bash
