name: 'Pandoc-Lecture'
description: 'This action will run the Pandoc-Lecture toolchain from https://github.com/cagix/pandoc-lecture (Ubuntu runner only)'

inputs:
  metadata:
    description: 'Metadata file (.yaml)'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Copy Makefile'
      run: cp ${{ github.action_path }}/Makefile .
      shell: bash

    - name: 'Copy Templates'
      run: cp -r ${{ github.action_path }}/.pandoc .
      shell: bash

    - name: 'Compile document'
      run: make  gfm  METADATA=${{ inputs.metadata }}
      shell: bash

    - name: 'ls -lags'
      run: ls -lags
      shell: bash
