# generated by pandoc -L crawl.lua
COURSE_MD_SOURCES := \
  readme.md \
  lecture/readme.md \
  lecture/02-parsing/readme.md \
  lecture/02-parsing/cfg.md \
  lecture/02-parsing/antlr-parsing.md \
  lecture/03-test/readme.md \
  lecture/03-test/test.md \
  lecture/03-test/nn02-linear-regression.md \
  lecture/03-test/subfolder/foo.md \
  homework/readme.md \
  homework/sheet04.md \
  homework/sheet01.md \
  homework/sheet02.md \
  homework/sheet03.md
