name: Handout (Docsify plus PDF)

on:
  # push on master branch
  push:
    branches: [master]
  # triggered manually
  workflow_dispatch:

jobs:
  handout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: cagix/pandoc-lecture-zen@master
        with:
          mktarget: handout
          metadata: cb.yaml
          output_dir: _handout
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _handout
          publish_branch: _handout    ## TODO (semester branch)
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
