name: TESTS

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_beamer:
    uses: ./.github/workflows/_build-materials.yaml
    with:
      mktarget: beamer
      metadata: cb.yaml
      build_path: _beamer
      publish: false

  test_docsify:
    uses: ./.github/workflows/_build-materials.yaml
    with:
      mktarget: docsify
      metadata: cb.yaml
      build_path: _docsify
      publish: false

  test_pdf:
    uses: ./.github/workflows/_build-materials.yaml
    with:
      mktarget: pdf
      metadata: cb.yaml
      build_path: _pdf
      publish: false
